import streamlit as st
import time
from mizan_core import app as mizan_app

# Page Config
st.set_page_config(
    page_title="Mizan: Fact, Not Fatwa",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Title
st.title("⚖️ Mizan: Fact, Not Fatwa")
st.caption("A Transparent 'Glass Box' AI for Quranic Reasoning (v3.0 Eloquent Scholar)")

# Sidebar: Brain Activity
st.sidebar.title("🧠 Brain Activity")
st.sidebar.markdown("---")

# Initialize Expanders (Placeholders)
exp_query = st.sidebar.expander("🔍 Query Analysis", expanded=False)
exp_evidence = st.sidebar.expander("📄 Evidence Retrieved", expanded=False)
exp_verification = st.sidebar.expander("✅ Verification Status", expanded=False)

# Session State for Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Chat Input
if prompt := st.chat_input("Ask a question about the Quran..."):
    # Add user message to history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Placeholder for assistant response
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        full_response = ""
        draft_answer = ""  # Variable to hold the answer before verification
        
        # Reset Sidebar Expanders for new query
        exp_query.empty()
        exp_evidence.empty()
        exp_verification.empty()
        
        # Stream Logic
        # We pass original_question. search_query is generated by the first node.
        inputs = {"original_question": prompt, "retry_count": 0}
        
        try:
            # We iterate through the graph updates
            for output in mizan_app.stream(inputs):
                
                # 1. Smart Query Expansion
                if 'smart_query_expansion' in output:
                    new_state = output['smart_query_expansion']
                    search_q = new_state.get("search_query", "")
                    with exp_query:
                        st.markdown(f"**Original:** {prompt}")
                        st.markdown(f"**Optimized:** {search_q}")
                        st.success("Query Optimized")
                
                # 2. Retrieval
                if 'retrieve' in output:
                    new_state = output['retrieve']
                    docs = new_state.get("documents", [])
                    with exp_evidence:
                        if docs:
                            for i, doc in enumerate(docs):
                                st.markdown(f"**Doc {i+1}** ({doc.metadata.get('source_id', 'Unknown')}):")
                                st.caption(doc.page_content[:200] + "...") # Truncate for display
                                st.markdown("---")
                            st.success(f"Retrieved {len(docs)} documents")
                        else:
                            st.warning("No documents found.")
                
                # 3. Grading (Optional, but good for transparency)
                if 'grade_documents' in output:
                    new_state = output['grade_documents']
                    retry_count = new_state.get("retry_count", 0)
                    filtered_docs = new_state.get("documents", [])
                    with exp_evidence:
                        st.info(f"Relevant Docs after Grading: {len(filtered_docs)}")
                        if retry_count > 0:
                            st.warning(f"Retried {retry_count} times")
                
                # 4. Generate Answer
                if 'generate_answer' in output:
                    new_state = output['generate_answer']
                    # Capture the draft answer
                    draft_answer = new_state.get("generation", "")
                    # Show status, do NOT show answer yet
                    message_placeholder.markdown("✍️ *Drafting scholar response...*")
                    
                # 5. Verify Citations
                if 'verify_citations' in output:
                    new_state = output['verify_citations']
                    status = new_state.get("citation_status", "Unknown")
                    
                    # Note: If verified, 'generation' might NOT be in new_state if the node didn't return it.
                    # We rely on draft_answer captured earlier.
                    # If failed, the node returns a new 'generation' with error message.
                    
                    with exp_verification:
                        if status == "Failed":
                            st.error("Verification Failed")
                            # If failed, the node returns the error message in 'generation'
                            error_msg = new_state.get("generation", "Verification failed.")
                            st.markdown(error_msg)
                            full_response = error_msg
                        elif status == "Verified":
                            st.success("Citations Verified")
                            st.markdown("All claims supported by context.")
                            # Use the draft answer
                            full_response = draft_answer
                        else:
                            st.warning(f"Unknown status: {status}")
                            full_response = draft_answer

                    # Update main chat with final answer
                    message_placeholder.markdown(full_response)
                    
            # Add assistant message to history
            st.session_state.messages.append({"role": "assistant", "content": full_response})
            
        except Exception as e:
            st.error(f"An error occurred: {e}")
